modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="nyfsarcheryplus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Nyf's Archer Plus" #mandatory
authors="TheNyfaria" #optional
description='''
This extends Minecraft Archery with 4 Tiers of Bows that just Increase Durability.
And 5 Tiers of Arrows (increased damage) made from the New item Arrow Tips
'''

